services:
  web:
    build: ../../../apps/web
    env_file: ../../../apps/web/.env
    volumes:
      - ../../../apps/web:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
    command: "npm run dev -- --hostname 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"

  api:
    build: ../../../apps/api
    env_file: ../../../apps/api/.env
    volumes:
      - ../../../apps/api:/var/www/api
    command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
